### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by 3553531421** [rockcor/GraphSlim#5]

**Comment by 3553531421** [comment]
![1733391462483](https://github.com/user-attachments/assets/2f4af8c3-1a54-4ead-bbdb-57318ca3c781)
i do not change the code,why it have this wrong

**Comment by LingFengGold** [comment]
Thank you for pointing out the bug. We have fixed it in commit [67e5327](https://github.com/Emory-Melody/GraphSlim/commit/67e5327c5216157faa6400ccb6e6224a4c737681).
