### ISSUE TITLE
A question about the node numbers about Cora

### ISSUE THREAD

**Issue by 3553531421** [rockcor/GraphSlim#6]
The data node in the Cora dataset seems to be incorrect. The complete node count is 2708, but the node counts for adj_train/val/test are 140/500/1000 (before reduction), which do not add up to 2708. Questions: 1. Reduce seems to only take effect on the training set. 2. The number of nodes in the Cora dataset is not very large, so why is the node count in the training set so small, and why doesn't it follow the 6:2:2 rule?

Here is the code I used:
![image](https://github.com/user-attachments/assets/cb6f19cd-7a4a-4539-a67b-df3769f78c25)

**Comment by rockcor** [comment]
Your question is about the dataset split in Cora. The 140/500/1000 split is the "public" split provided by [PyG](https://pytorch-geometric.readthedocs.io/en/2.5.0/generated/torch_geometric.datasets.Planetoid.html) and is the original split in GCN paper (Kipf et al, 2016). Most of graph condensation papers are follwing this split currently. 
Besides, grap condensation will use all the nodes and whole adj in graphs with transductive setting, e.g., Cora. However, for other reduction methods, GraphSlim mostly only uses the training nodes following GCond (Jin et al., 2021) paper.
Feel free if you have further questions.

**Comment by 3553531421** [comment]
Thank you for your patient answer. Because I am not a graph compression person, I am not clear about the ratio of the number of nodes compressed. 6:2:2 is the classification ratio of the data set that I came into contact with.Your answer tells me a lot more






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月20日(星期五) 凌晨3:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Emory-Melody/GraphSlim] A question about the node numbers about Cora (Issue #6)














 
Your question is about the dataset split in Cora. The 140/500/1000 split is the "public" split provided by PyG and is the original split in GCN paper (Kipf et al, 2016). Most of graph condensation papers are follwing this split currently.
 Besides, grap condensation will use all the nodes and whole adj in graphs with transductive setting, e.g., Cora. However, for other reduction methods, GraphSlim mostly only uses the training nodes following GCond (Jin et al., 2021) paper.
 Feel free if you have further questions.
